version: 2
workflows:
  version: 2
  test:
    jobs:
      - test-3.6-buster
      - test-3.7-buster
      - test-3.8-buster
      - test-3.9-buster
jobs:
  test-3.7-buster: &test-template
    docker:
      - image: circleci/python:3.7-buster
    steps:
      - checkout
      - run:
          name: Install OS and Python prerequisites
          command: |
            sudo apt-get -y update
            sudo apt-get -y install \
              -o APT::Install-Suggests=false \
              -o APT::Install-Recommends=false \
              qemu qemu-system-arm qemu-system-x86 \
              libvirt-dev libvirt-daemon libvirt-daemon-system \
              libvirt-clients nmap
            virtualenv cowrie-env
            . cowrie-env/bin/activate
            pip install libvirt-python==6.9.0
            pip install -r requirements.txt
            pip install -r requirements-dev.txt
      - run:
          command: |
            . cowrie-env/bin/activate
            pip check
      - run:
          name: Lint
          command: |
            . cowrie-env/bin/activate
            flake8 --ignore E203,E501,W503 --count --application-import-names cowrie --statistics src
      - run:
          name: Build Python library
          command: |
            . cowrie-env/bin/activate
            python setup.py build sdist bdist
      - run:
          name: Build documentation
          command: |
            . cowrie-env/bin/activate
            make -C docs html
      - run:
          name: Run unit tests
          command: |
            . cowrie-env/bin/activate
            PYTHONPATH=`pwd`/src trial cowrie
  test-3.6-buster:
    <<: *test-template
    docker:
      - image: circleci/python:3.6-buster
  test-3.8-buster:
    <<: *test-template
    docker:
      - image: circleci/python:3.8-buster
  test-3.9-buster:
    <<: *test-template
    docker:
      - image: circleci/python:3.9-buster
  test-3.10-buster:
    <<: *test-template
    docker:
      - image: circleci/python:3.10-buster
